name: mimi
description: Mobile app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_bloc: ^6.1.0
  test: ^1.15.2
  bloc_test: ^7.1.0
  equatable: ^1.2.5
  font_awesome_flutter: ^8.7.0
  google_fonts: ^1.1.1
  shared_preferences: ^0.5.12+4
  pedantic: ^1.9.0
  page_transition: ^1.1.7+2
  beauty_textfield: ^0.0.1
  image_picker: ^0.6.7+14
  loading_indicator: ^1.2.0
  ff_navigation_bar: ^0.1.5
  percent_indicator: ^2.1.8
  flutter_xlider: ^3.4.0
  flutter_date_pickers: ^0.1.8
  getwidget: ^1.2.4
  http: ^0.12.2
  intl: ^0.16.1

  authentication:
    path: lib/repositories/authentication
  users:
    path: lib/repositories/users
  storage:
    path: lib/repositories/storage
  data:
    path: lib/repositories/data

  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/